# Generated by Django 2.2.9 on 2020-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200901_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, help_text='Напишите что-нибудь содержательное', verbose_name='Текст комментария'),
        ),
    ]
